function [F] = fid_tmsv_ri(V, gx, gp, modes, sigma)
warning('off')

switch modes
    case '1'
        % send mode B
        F=...
            integralN(@(r,theta,ra,ri)...
            exp(-(ra.^2 + ri.^2)./sigma).*1/(pi*sigma).*...
            (exp(1).^((1/8).*r.*((sqrt(-1)*8).*(1+gx).*ri.*cos(theta)+r.*((-7)+ ...
  (-1).*V+gx.*((-2)+2.*V+(-4).*((-1)+V.^2).^(1/2))+gx.^2.*((-3)+(-5) ...
  .*V+4.*((-1)+V.^2).^(1/2))).*cos(theta).^2+sin(theta).*((sqrt(-1)* ...
  (-8)).*(1+gp).*ra+r.*((-7)+(-1).*V+gp.*((-2)+2.*V+(-4).*((-1)+ ...
 V.^2).^(1/2))+gp.^2.*((-3)+(-5).*V+4.*((-1)+V.^2).^(1/2))).*sin( ...
  theta)))).*pi.^(-1).*r)...
            ,0,inf,0,2*pi,-3*sigma,3*sigma,-3*sigma,3*sigma);
    
    case '2'
        F=...
            integralN(@(r,theta,ra,ri)...
            exp(-(ra.^2 + ri.^2)./sigma).*1/(pi*sigma).*...
            (exp(1).^((1/8).*r.*((sqrt(-1)*(-8)).*((-1)+gx).*ri.*cos(theta)+r.* ...
  ((-7)+(-1).*V+gx.^2.*((-3)+(-5).*V+4.*((-1)+V.^2).^(1/2))+gx.*(2+( ...
  -2).*V+4.*((-1)+V.^2).^(1/2))).*cos(theta).^2+sin(theta).*((sqrt( ...
  -1)*8).*((-1)+gp).*ra+r.*((-7)+(-1).*V+gp.^2.*((-3)+(-5).*V+4.*(( ...
  -1)+V.^2).^(1/2))+gp.*(2+(-2).*V+4.*((-1)+V.^2).^(1/2))).*sin( ...
 theta)))).*pi.^(-1).*r)...
            ,0,inf,0,2*pi,-3*sigma,3*sigma,-3*sigma,3*sigma);
      
    case '3'
        F=...
            integralN(@(r,theta,ra,ri)...
            exp(-(ra.^2 + ri.^2)./sigma).*1/(pi*sigma).*...
            (exp(1).^((-1/4).*r.^2.*(4+gx.^2+gx.^2.*V+gp.^2.*(1+V)+(-1).*( ...
gp.^2+(-1).*gx.^2).*(1+V).*cos(2.*theta))).*pi.^(-1).*r)...
            ,0,inf,0,2*pi,-3*sigma,3*sigma,-3*sigma,3*sigma);
    
    case '12'
        F=...
            integralN(@(r,theta,ra,ri)...
            exp(-(ra.^2 + ri.^2)./sigma).*1/(pi*sigma).*...
            (exp(1).^((1/4).*r.*((-4).*r+(-1).*gp.^2.*r+(-1).*gx.^2.*r+(-1).* ...
 gp.^2.*r.*V+(-1).*gx.^2.*r.*V+(sqrt(-1)*8).*ri.*cos(theta)+(gp.^2+ ...
  (-1).*gx.^2).*r.*(1+V).*cos(2.*theta)+(sqrt(-1)*(-8)).*ra.*sin( ...
  theta))).*pi.^(-1).*r)...
            ,0,inf,0,2*pi,-3*sigma,3*sigma,-3*sigma,3*sigma);
        
    
    case '13'
        F=...
            integralN(@(r,theta,ra,ri)...
            exp(-(ra.^2 + ri.^2)./sigma).*1/(pi*sigma).*...
            (exp(1).^((1/16).*r.*((-14).*r+2.*gp.*r+(-3).*gp.^2.*r+(-2).*gx.*r+ ...
  (-3).*gx.^2.*r+(-2).*r.*V+2.*gp.*r.*V+(-1).*gp.^2.*r.*V+2.*gx.*r.* ...
  V+(-1).*gx.^2.*r.*V+(sqrt(-1)*16).*(1+gx).*ri.*cos(theta)+r.*((-2) ...
  .*gp.*(1+V)+gp.^2.*(3+V)+(-1).*gx.*(2+(-2).*V+gx.*(3+V))).*cos(2.* ...
  theta)+(sqrt(-1)*(-16)).*ra.*sin(theta)+(sqrt(-1)*(-16)).*gp.*ra.* ...
  sin(theta))).*pi.^(-1).*r)...
            ,0,inf,0,2*pi,-3*sigma,3*sigma,-3*sigma,3*sigma);
        
    
    case '23'
        F=...
            integralN(@(r,theta,ra,ri)...
            exp(-(ra.^2 + ri.^2)./sigma).*1/(pi*sigma).*...
            (exp(1).^((1/16).*r.*((-14).*r+2.*gp.*r+(-7).*gp.^2.*r+2.*gx.*r+( ...
 -7).*gx.^2.*r+(-2).*r.*V+(-2).*gp.*r.*V+(-1).*gp.^2.*r.*V+(-2).* ...
  gx.*r.*V+(-1).*gx.^2.*r.*V+(sqrt(-1)*(-16)).*((-1)+gx).*ri.*cos( ...
  theta)+(gp+(-1).*gx).*r.*((-2)+7.*gx+2.*V+gx.*V+gp.*(7+V)).*cos( ...
  2.*theta)+(sqrt(-1)*(-16)).*ra.*sin(theta)+(sqrt(-1)*16).*gp.*ra.* ...
  sin(theta))).*pi.^(-1).*r)...
            ,0,inf,0,2*pi,-3*sigma,3*sigma,-3*sigma,3*sigma);
        
    case '123'
        F=...
            integralN(@(r,theta,ra,ri)...
            exp(-(ra.^2 + ri.^2)./sigma).*1/(pi*sigma).*...
            (exp(1).^((-1).*r.*(r+(sqrt(-1)*(-2)).*ri.*cos(theta)+(sqrt(-1)*2) ...
  .*ra.*sin(theta))).*pi.^(-1).*r)...
            ,0,inf,0,2*pi,-3*sigma,3*sigma,-3*sigma,3*sigma);
end

F = real(F);

end